# Generated by Django 5.2.17 on 2026-09-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0001_initial'),
        ('leads', '0003_leadactivity_leadnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('sub_industry', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', help_text='Free-text location filter (city/state or region).', max_length=120)),
                ('minimum_lead_score', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('daily_limit', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('recommended_service', models.CharField(blank=True, default='', max_length=180)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('meeting_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0, editable=False)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_engine.emailtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='leads.lead')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-created_at'], name='campaigns_c_status_db0aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['campaign', 'send_status'], name='campaigns_c_campaig_0ff376_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignlead',
            unique_together={('campaign', 'lead')},
        ),
    ]
