# Generated by Django 5.2.17 on 2026-09-23 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('default_recommended_service', models.CharField(blank=True, default='', max_length=180)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
