# Generated by Django 5.2.17 on 2026-09-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='last name')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='full name')),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='job title')),
                ('email', models.EmailField(blank=True, max_length=320, verbose_name='e-mail')),
                ('normalized_email', models.CharField(blank=True, db_index=True, editable=False, max_length=320, verbose_name='normalized e-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=32, verbose_name='normalized phone')),
                ('phone_type', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MOBILE', 'Mobile'), ('LANDLINE', 'Landline'), ('OFFICE', 'Office'), ('OTHER', 'Other')], default='UNKNOWN', max_length=16, verbose_name='phone type')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ('full_name', 'id'),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='contact_name_idx'), models.Index(fields=['company', 'full_name'], name='contact_company_name_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('company__isnull', False), models.Q(('normalized_email', ''), _negated=True)), fields=('company', 'normalized_email'), name='contact_unique_email_per_company')],
            },
        ),
    ]
