# Generated by Django 5.2.17 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_normalized_address_and_more'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='normalized name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'normalized_name'], name='contact_company_norm_name_idx'),
        ),
    ]
