# Generated by Django 5.2.17 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='company name')),
                ('normalized_name', models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='normalized name')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='industry')),
                ('sub_industry', models.CharField(blank=True, max_length=150, verbose_name='sub industry')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('normalized_website', models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='normalized website')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=32, verbose_name='normalized phone')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='street address')),
                ('city', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='city')),
                ('state', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='zip code')),
                ('country', models.CharField(blank=True, default='United States', max_length=120, verbose_name='country')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='employee count')),
                ('source', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='source')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['state', 'city'], name='company_state_city_idx'), models.Index(fields=['industry', 'state'], name='company_industry_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('normalized_website', ''), _negated=True), fields=('normalized_website',), name='company_unique_normalized_website'), models.CheckConstraint(condition=models.Q(('employee_count__isnull', True), ('employee_count__gte', 0), _connector='OR'), name='company_employee_count_non_negative')],
            },
        ),
    ]
