# Generated by Django 5.2.17 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='normalized_address',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=500, verbose_name='normalized address'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['normalized_name', 'city', 'state'], name='company_name_city_state_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['normalized_phone'], name='company_norm_phone_idx'),
        ),
    ]
