# Generated by Django 5.2.17 on 2026-09-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='lead score')),
                ('lead_status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('MEETING', 'Meeting'), ('PROPOSAL', 'Proposal'), ('WON', 'Won'), ('LOST', 'Lost'), ('DO_NOT_CONTACT', 'Do not contact')], db_index=True, default='NEW', max_length=20, verbose_name='lead status')),
                ('email_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed'), ('SUPPRESSED', 'Suppressed')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='e-mail status')),
                ('source', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='source')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='source file')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='source row number')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company', verbose_name='company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='contacts.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['lead_status', '-lead_score'], name='lead_status_score_idx'), models.Index(fields=['lead_status', 'email_status'], name='lead_status_email_idx'), models.Index(fields=['-created_at'], name='lead_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lead_score__gte', 0), ('lead_score__lte', 100)), name='lead_score_between_0_and_100'), models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('company', 'contact'), name='lead_unique_contact_per_company')],
            },
        ),
    ]
