# Generated by Django 5.2.17 on 2026-09-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='merged at'),
        ),
        migrations.AddField(
            model_name='lead',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='leads.lead', verbose_name='merged into'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('MEETING', 'Meeting'), ('PROPOSAL', 'Proposal'), ('WON', 'Won'), ('LOST', 'Lost'), ('DO_NOT_CONTACT', 'Do not contact'), ('MERGED', 'Merged')], db_index=True, default='NEW', max_length=20, verbose_name='lead status'),
        ),
    ]
