# Generated by Django 5.2.17 on 2026-09-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_merged_at_lead_merged_into_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('IMPORTED', 'Imported'), ('STATUS_CHANGE', 'Status change'), ('SCORE_CHANGE', 'Score change'), ('NOTE_ADDED', 'Note added'), ('EMAIL_SENT', 'E-mail sent'), ('EMAIL_OPENED', 'E-mail opened'), ('REPLY', 'Reply'), ('MEETING', 'Meeting booked'), ('MERGED', 'Merged'), ('SUPPRESSED', 'Suppressed'), ('BULK_EDIT', 'Bulk edit'), ('CAMPAIGN_ADDED', 'Added to campaign'), ('EXPORTED', 'Exported'), ('NOTE', 'Note'), ('MANUAL_EDIT', 'Manual edit')], db_index=True, max_length=24, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.CharField(blank=True, max_length=120, verbose_name='actor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'lead activity',
                'verbose_name_plural': 'lead activities',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_activity_lead_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='body')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='author')),
                ('pinned', models.BooleanField(db_index=True, default=False, verbose_name='pinned')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'lead note',
                'verbose_name_plural': 'lead notes',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_note_lead_created_idx')],
            },
        ),
    ]
