# Generated by Django 5.2.17 on 2026-09-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_merged_at_lead_merged_into_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('EMAIL', 'Same normalized e-mail'), ('COMPANY_WEBSITE', 'Same company + website'), ('COMPANY_PHONE', 'Same company + phone'), ('COMPANY_ADDRESS', 'Same company + address'), ('COMPANY_CITY_STATE', 'Same company + city + state'), ('CONTACT_NAME_COMPANY', 'Same contact name + company')], max_length=32, verbose_name='reason code')),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, verbose_name='confidence')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MERGED', 'Merged'), ('KEPT_BOTH', 'Kept both'), ('IGNORED', 'Ignored')], db_index=True, default='OPEN', max_length=16, verbose_name='status')),
                ('cluster_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='cluster key')),
                ('resolved_by', models.CharField(blank=True, max_length=120, verbose_name='resolved by')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('surviving_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.lead', verbose_name='surviving lead')),
            ],
            options={
                'verbose_name': 'duplicate group',
                'verbose_name_plural': 'duplicate groups',
                'ordering': ('-confidence', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DuplicateGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=10, verbose_name='role')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='data_quality.duplicategroup', verbose_name='group')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_memberships', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'duplicate group member',
                'verbose_name_plural': 'duplicate group members',
                'ordering': ('role', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('EMAIL', 'Same normalized e-mail'), ('COMPANY_WEBSITE', 'Same company + website'), ('COMPANY_PHONE', 'Same company + phone'), ('COMPANY_ADDRESS', 'Same company + address'), ('COMPANY_CITY_STATE', 'Same company + city + state'), ('CONTACT_NAME_COMPANY', 'Same contact name + company')], max_length=32, verbose_name='reason code')),
                ('confidence', models.PositiveSmallIntegerField(verbose_name='confidence')),
                ('fields_from_merged', models.JSONField(blank=True, default=dict, verbose_name='fields taken from the merged record')),
                ('merged_sources', models.JSONField(blank=True, default=list, verbose_name='preserved source list')),
                ('performed_by', models.CharField(blank=True, max_length=120, verbose_name='performed by')),
                ('duplicate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges', to='data_quality.duplicategroup', verbose_name='duplicate group')),
                ('merged_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_losers', to='leads.lead', verbose_name='merged lead')),
                ('surviving_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_winners', to='leads.lead', verbose_name='surviving lead')),
            ],
            options={
                'verbose_name': 'merge audit',
                'verbose_name_plural': 'merge audits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='duplicategroup',
            index=models.Index(fields=['status', '-confidence'], name='dq_status_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicategroup',
            index=models.Index(fields=['reason_code', 'status'], name='dq_reason_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='duplicategroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'lead'), name='dq_member_unique_per_group'),
        ),
        migrations.AddIndex(
            model_name='mergeaudit',
            index=models.Index(fields=['surviving_lead'], name='dq_merge_winner_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeaudit',
            index=models.Index(fields=['merged_lead'], name='dq_merge_loser_idx'),
        ),
    ]
