# Generated by Django 5.2.17 on 2026-09-23 16:11

import apps.imports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16, verbose_name='status')),
                ('upload', models.FileField(blank=True, upload_to=apps.imports.models.upload_path, verbose_name='file')),
                ('file_type', models.CharField(blank=True, max_length=8, verbose_name='file type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='file size')),
                ('encoding', models.CharField(blank=True, max_length=32, verbose_name='encoding')),
                ('delimiter', models.CharField(blank=True, max_length=4, verbose_name='delimiter')),
                ('sheet_names', models.JSONField(blank=True, default=list, verbose_name='sheets')),
                ('selected_sheet', models.CharField(blank=True, max_length=255, verbose_name='selected sheet')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='source columns')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='column mapping')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='analysis')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='processed rows')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='valid rows')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='invalid rows')),
                ('duplicate_rows', models.PositiveIntegerField(default=0, verbose_name='duplicate rows')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='error rows')),
                ('missing_email_rows', models.PositiveIntegerField(default=0, verbose_name='rows without e-mail')),
                ('new_companies', models.PositiveIntegerField(default=0, verbose_name='new companies')),
                ('new_contacts', models.PositiveIntegerField(default=0, verbose_name='new contacts')),
                ('issues', models.JSONField(blank=True, default=list, verbose_name='issues')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'import job',
                'verbose_name_plural': 'import jobs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='import_status_created_idx'), models.Index(fields=['filename'], name='import_filename_idx')],
            },
        ),
    ]
